version: "3.8"

services:
  app:
    container_name: ViviendeaApp
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of PHP version: 8, 8.1, 8.0, 7, 7.4
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "8"
        # Optional Node.js version
        NODE_VERSION: "18"
      #volumes:
      #- ..:/workspace:default

      # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - "9222:9222"
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: bridge
    links:
      - db
      - cache
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  db:
    container_name: db
    image: mariadb:10.4
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: viviendea_lmv
      MYSQL_USER: webapp
      MYSQL_PASSWORD: viviendea*11334
    # Add "forwardPorts": ["3306"] to **devcontainer.json** to forward MariaDB locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
volumes:
  mariadb-data: null
